package com.onlineteachers.teacher

import android.Manifest
import android.content.Intent
import android.net.Uri
import android.provider.Settings
import android.content.pm.PackageManager
import android.os.Build
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.core.app.NotificationManagerCompat
import androidx.core.content.ContextCompat
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.onlineteachers.shared.*

class MainActivity : ComponentActivity() {
    private lateinit var vault: Vault
    private var preview: Playback? = null
    private val permissions = registerForActivityResult(ActivityResultContracts.RequestMultiplePermissions()) {
        TeacherStatus.status.value = if (canActivate()) "Permissions granted — tap Activate Monitoring" else "Permission denied — enable camera, microphone and notifications in Android Settings"
    }
    private fun canActivate(): Boolean = ActivationPolicy.mayActivate(
        ContextCompat.checkSelfPermission(this, Manifest.permission.CAMERA) == PackageManager.PERMISSION_GRANTED,
        ContextCompat.checkSelfPermission(this, Manifest.permission.RECORD_AUDIO) == PackageManager.PERMISSION_GRANTED,
        NotificationManagerCompat.from(this).areNotificationsEnabled(),
        lifecycle.currentState.isAtLeast(androidx.lifecycle.Lifecycle.State.RESUMED)
    )
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState); vault = Vault(this)
        setContent {
            SchoolTheme {
                val active by TeacherStatus.active.collectAsStateWithLifecycle()
                val status by TeacherStatus.status.collectAsStateWithLifecycle()
                val code by TeacherStatus.pairingCode.collectAsStateWithLifecycle()
                var address by remember { mutableStateOf(runCatching { vault.get("address") }.getOrDefault("")) }
                var key by remember { mutableStateOf(runCatching { vault.get("key") }.getOrDefault("")) }
                var confirmReset by remember { mutableStateOf(false) }
                SchoolPage("Classroom phone") {
                    Text("Your camera and microphone are shared live with one paired administrator while monitoring is active. No recording is saved by these apps or the relay.")
                    StatusCard(status)
                    if (active) {
                        VideoSurface(Modifier.fillMaxWidth().height(260.dp)) { surface ->
                            if (surface != null && preview == null) {
                                preview = Playback({ TeacherStatus.service?.previewKey() }, {}).also { it.muted = true }
                                TeacherStatus.localPreview = { frame -> if (frame.kind == 1) preview?.accept(frame) }
                            }
                            preview?.surface(surface)
                        }
                        Text("Local preview • Capture continues when minimized or locked. Your phone may stop it to protect battery or privacy.", style = MaterialTheme.typography.bodySmall)
                        Button(onClick = { stopService(Intent(this@MainActivity, MonitoringService::class.java)) }, modifier = Modifier.fillMaxWidth(), colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.error)) { Text("STOP MONITORING") }
                        OutlinedButton(onClick = { TeacherStatus.service?.pair() }, modifier = Modifier.fillMaxWidth()) { Text("Show one-time pairing code") }
                        if (code.isNotBlank()) Text(code, style = MaterialTheme.typography.headlineSmall)
                        Text("A code expires after 2 minutes. Share it only with your administrator.")
                        TextButton(onClick = { confirmReset = true }) { Text("Reset pairing on this phone") }
                    } else {
                        SettingsFields(address, { address = it.trim() }, key, { key = it.trim() }, true)
                        Text("Use the Teacher setup key generated by the server operator. Never use the Admin key here.", style = MaterialTheme.typography.bodySmall)
                        Button(onClick = {
                            if (!RelayClient.validAddress(address) || !RelayClient.validKey(key)) {
                                TeacherStatus.status.value = "Enter a valid wss:// address ending /ws and the 43-character Teacher key"
                            } else if (!canActivate()) {
                                val required = mutableListOf(Manifest.permission.CAMERA, Manifest.permission.RECORD_AUDIO)
                                if (Build.VERSION.SDK_INT >= 33) required.add(Manifest.permission.POST_NOTIFICATIONS)
                                permissions.launch(required.toTypedArray())
                            } else {
                                runCatching {
                                    vault.put("address", address); vault.put("key", key)
                                    ContextCompat.startForegroundService(this@MainActivity, Intent(this@MainActivity, MonitoringService::class.java))
                                }.onFailure { TeacherStatus.status.value = "Cannot activate — check Android permissions and settings" }
                            }
                        }, modifier = Modifier.fillMaxWidth()) { Text("Activate Monitoring") }
                        TextButton(onClick = { startActivity(Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS, Uri.parse("package:$packageName"))) }) { Text("Open Android permission / notification settings") }
                        Text("Activation is always local. After reboot, force-stop, Stop, or service termination, return here and activate again.")
                        TextButton(onClick = { vault.clear(); key = ""; address = "" }) { Text("Clear saved setup") }
                    }
                }
                if (confirmReset) AlertDialog(onDismissRequest = { confirmReset = false }, title = { Text("Disconnect paired administrator?") }, text = { Text("Live viewing ends immediately. A new code from this phone will be required.") }, confirmButton = {
                    TextButton(onClick = { TeacherStatus.service?.resetPairing(); confirmReset = false }) { Text("Reset pairing") }
                }, dismissButton = { TextButton(onClick = { confirmReset = false }) { Text("Cancel") } })
            }
        }
    }
    override fun onStop() {
        TeacherStatus.localPreview = null; preview?.close(); preview = null
        super.onStop()
    }
}
